apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: ipi-internal-lmn8w 
  name: ipi-internal-lmn8w-infra-a 
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: ipi-internal-lmn8w 
      machine.openshift.io/cluster-api-machineset: ipi-internal-lmn8w-infra-a 
  template:
    metadata:
      creationTimestamp: null
      labels:
        machine.openshift.io/cluster-api-cluster: ipi-internal-lmn8w 
        machine.openshift.io/cluster-api-machine-role: infra 
        machine.openshift.io/cluster-api-machine-type: infra 
        machine.openshift.io/cluster-api-machineset: ipi-internal-lmn8w-infra-a 
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/infra: "" 
      taints:
      - effect: NoSchedule
        key: infra
        value: reserved
      - effect: NoExecute
        key: infra
        value: reserved
      providerSpec:
        value:
          apiVersion: gcpprovider.openshift.io/v1beta1
          canIPForward: false
          credentialsSecret:
            name: gcp-cloud-credentials
          deletionProtection: false
          disks:
          - autoDelete: true
            boot: true
            image: projects/rhcos-cloud/global/images/rhcos-47-83-202103251640-0-gcp-x86-64
            labels: null
            sizeGb: 128
            type: pd-ssd
          kind: GCPMachineProviderSpec
          machineType: n1-standard-4
          metadata:
            creationTimestamp: null
          networkInterfaces:
          - network: ipi-internal-lmn8w-network 
            subnetwork: ipi-internal-lmn8w-worker-subnet 
          projectID: pescorza-tam-ocp-cee 
          region: europe-west2
          serviceAccounts:
          - email: ipi-internal-lmn8w-w@pescorza-tam-ocp-cee.iam.gserviceaccount.com   
            scopes:
            - https://www.googleapis.com/auth/cloud-platform
          tags:
          - ipi-internal-lmn8w-worker 
          userDataSecret:
            name: worker-user-data
          zone: europe-west2-a
      
